---
- name: Create /home/app.txt file on all app servers
  hosts: app_servers
  become: yes
  tasks:
    - name: Create the file /home/app.txt
      file:
        path: /home/app.txt
        state: touch

    - name: Set permissions of /home/app.txt to 0655
      file:
        path: /home/app.txt
        mode: '0655'

    - name: Set ownership based on inventory file
      file:
        path: /home/app.txt
        owner: "{{ hostvars[inventory_hostname].user }}"
        group: "{{ hostvars[inventory_hostname].group }}"
