---
- name: Create /home/app.txt file on all app servers
  hosts: app_servers
  become: yes
  tasks:
    - name: Create the file /home/app.txt
      file:
        path: /home/app.txt
        state: touch
        mode: '0655'

    - name: Set ownership based on ansible_user
      file:
        path: /home/app.txt
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
