---
- name: Fetch Log File and Check for Errors
  hosts: webservers
  tasks:
    - name: Slurp the error log file
      slurp:
        src: /var/log/myapp/error.log
      register: log_content

    - name: Decode the log content
      set_fact:
        decoded_log: "{{ log_content.content | b64decode }}"

    - name: Check for specific error in the log
      debug:
        msg: "Error found in log file!"
      when: "'Critical error' in decoded_log"

    - name: Send email if critical error is found
      mail:
        to: "admin@example.com"
        subject: "Critical Error in Application Log"
        body: "A critical error has been detected in the application logs."
      when: "'Critical error' in decoded_log"
